### ISSUE TITLE
Helicopters added to dynamic simulation fail to follow move commands

### ISSUE THREAD

**Issue by Radeni** [nicholasclark-artist/DCG#101] opened 2017-03-30 14:27 UTC
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `latest`
**DCG Version:** `3.2.0`

**Server Mods:**
- `@CBA_A3`
- `@dcg`

**Description:**
- Helicopter Transport Support module (Virtual) doesnt work properly when DCG mod is running on the server (Regardless of DCG Transport). Once the helicopter is called in it will come and land where you called it,waiting for you to get in and give it coordinates to transport you to. This is where the issue occurs,once the helicopter had been given the coordinates, it wont take off,the pilot will just tell you the standard message that you arrived at your destination and thats it.
Note: This works fine in singleplayer (With and without DCG) and in multiplayer (without DCG) on the same mission file.

**Additional info:** I can create a video to demonstrate what is going on

**Steps to reproduce:**
- Set up transport support module (virtual) synced to player and run in multiplayer. After that call in support and do as mentioned above.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**RPT log file:**
[Arma3_x64_2017-03-30_16-00-58.txt](https://github.com/nicholasclark-artist/DCG/files/882714/Arma3_x64_2017-03-30_16-00-58.txt)

Edit: Tested on multiple maps and missions

**Comment by nicholasclark-artist** [comment] 2017-03-30 15:33
This is probably due to DCG caching the transport's group. For now, call `[group _transport] call dcg_cache_fnc_disableCache` on the server.

**Comment by Radeni** [comment] 2017-03-30 17:40
How can it cache a helicopter that is right next to the player?

**Comment by nicholasclark-artist** [comment] 2017-03-30 19:40
The issue isn't that it's currently cached. The issue is that once a helicopter is added to Arma's dynamic simulation system (Bohemia's new caching solution) the helicopter fails to follow move/doMove commands in some cases.

**Comment by Radeni** [comment] 2017-03-30 20:54
Ah,alright,anything i can do as a temporary solution? where do i execute '[group _transport] call dcg_cache_fnc_disableCache' and are you sure its spelled properly

**Comment by nicholasclark-artist** [comment] 2017-03-30 21:06
Execute it on the server. The parameter should be the transport's group. So if your transport is called heli_01 it'd be `[group heli_01] call dcg_cache_fnc_disableCache`

**Comment by Radeni** [comment] 2017-03-30 21:30
the helicopter doesnt have a variable name because its a virtual module but it has an init field so i ghuess i can do` [_this] call dcg_cache_fnc_disableCache`

**Comment by Radeni** [comment] 2017-03-30 22:13
Update: For Virtual version of support module for helicopter transport adding `[group _this] call dcg_cache_fnc_disableCache` to the module's vehicle init fixed the issue,same can be done for normal transport module (but inside of the specific helicopter). Hope you manage to globally fix this issue for 3.2.1 ;)

**Comment by nicholasclark-artist** [comment] 2017-03-30 23:26
This isn't an issue specific to DCG. The cache addon is based on Bohemia's Dynamic Simulation system, so the issue would have to be fixed on that end.

**Closed** 2017-03-31 00:44 UTC
